import { Ionicons } from '@expo/vector-icons';
import { useQueryClient } from '@tanstack/react-query';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, Text, View } from 'react-native';

import { Avatar } from '@/components/ui/Avatar';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { EmptyState } from '@/components/ui/EmptyState';
import { Input } from '@/components/ui/Input';
import { colors } from '@/constants/theme';
import { useContacts } from '@/hooks/useContacts';
import { useDeleteTransaction } from '@/hooks/useTransactions';
import { confirm, notify } from '@/lib/confirm';
import { supabase } from '@/lib/supabase';
import type { TransactionRow } from '@/types/database';
import { formatMoney, parseUserAmount } from '@/utils/currency';
import { formatDate } from '@/utils/date';

async function fetchTransaction(id: string): Promise<TransactionRow> {
  const { data, error } = await supabase
    .from('transactions')
    .select('*')
    .eq('id', id)
    .single();
  if (error) throw error;
  return data as TransactionRow;
}

async function updateTransaction(
  id: string,
  patch: { amount?: number; description?: string | null },
): Promise<TransactionRow> {
  const { data, error } = await supabase
    .from('transactions')
    .update(patch)
    .eq('id', id)
    .select()
    .single();
  if (error) throw error;
  return data as TransactionRow;
}

export default function TransactionDetailScreen() {
  const { t } = useTranslation();
  const router = useRouter();
  const queryClient = useQueryClient();
  const { id } = useLocalSearchParams<{ id: string }>();

  const contactsQ = useContacts({});
  const deleteTxn = useDeleteTransaction();

  const [txn, setTxn] = useState<TransactionRow | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [editing, setEditing] = useState(false);
  const [amount, setAmount] = useState('');
  const [description, setDescription] = useState('');
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    if (!id) return;
    let cancelled = false;
    void (async () => {
      setLoading(true);
      setError(null);
      try {
        const row = await fetchTransaction(id);
        if (!cancelled) {
          setTxn(row);
          setAmount(row.amount);
          setDescription(row.description ?? '');
        }
      } catch (err) {
        if (!cancelled) setError((err as Error).message ?? t('errors.unknown'));
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [id, t]);

  if (loading) {
    return (
      <SafeAreaView className="flex-1 items-center justify-center bg-ink-50 dark:bg-ink-900">
        <ActivityIndicator size="large" color={colors.brand[500]} />
      </SafeAreaView>
    );
  }

  if (error || !txn) {
    return (
      <SafeAreaView className="flex-1 bg-ink-50 dark:bg-ink-900">
        <EmptyState
          icon="❓"
          title={t('transactions.notFound')}
          action={{ label: t('common.cancel'), onPress: () => router.back() }}
        />
      </SafeAreaView>
    );
  }

  const contact = txn.contact_id
    ? (contactsQ.data ?? []).find((c) => c.id === txn.contact_id) ?? null
    : null;
  const isIncome = txn.type === 'income';
  const heroBg = isIncome ? 'bg-income-500' : 'bg-expense-500';
  const sign = isIncome ? '+' : '−';
  const heroIcon = isIncome ? 'arrow-up-circle' : 'arrow-down-circle';
  const isAutoGenerated = txn.auto_generated;

  const onSave = async () => {
    const parsed = parseUserAmount(amount);
    if (parsed === null) {
      notify(t('app.name'), t('validation.amountInvalid'));
      return;
    }
    setSaving(true);
    try {
      const updated = await updateTransaction(txn.id, {
        amount: parsed,
        description: description.trim() ? description.trim() : null,
      });
      setTxn(updated);
      setAmount(updated.amount);
      setDescription(updated.description ?? '');
      setEditing(false);
      void queryClient.invalidateQueries({ queryKey: ['transactions'] });
      void queryClient.invalidateQueries({ queryKey: ['summary'] });
    } catch (err) {
      notify(t('app.name'), (err as Error).message ?? t('errors.unknown'));
    } finally {
      setSaving(false);
    }
  };

  const onDelete = async () => {
    const ok = await confirm({
      title: t('transactions.delete'),
      message: t('transactions.deleteConfirm'),
      confirmLabel: t('transactions.delete'),
      cancelLabel: t('common.cancel'),
      destructive: true,
    });
    if (!ok) return;
    try {
      await deleteTxn.mutateAsync(txn.id);
      router.back();
    } catch (err) {
      notify(t('app.name'), (err as Error).message ?? t('errors.unknown'));
    }
  };

  return (
    <SafeAreaView className="flex-1 bg-ink-50 dark:bg-ink-900">
      <View className={`px-5 pb-7 pt-3 ${heroBg}`}>
        <View className="flex-row items-center justify-between">
          <Pressable
            accessibilityRole="button"
            accessibilityLabel={t('common.cancel')}
            onPress={() => (editing ? setEditing(false) : router.back())}
            className="h-10 w-10 items-center justify-center rounded-full bg-white/15"
          >
            <Ionicons name="chevron-back" size={20} color="#fff" />
          </Pressable>
          <View className="flex-row items-center gap-1.5 rounded-full bg-white/15 px-3 py-1">
            <Ionicons name={heroIcon} size={14} color="#fff" />
            <Text className="text-xs font-semibold uppercase tracking-widest text-white">
              {isIncome ? t('quickAdd.income') : t('quickAdd.expense')}
            </Text>
          </View>
          {!editing && !isAutoGenerated ? (
            <Pressable
              accessibilityRole="button"
              accessibilityLabel={t('contacts.edit')}
              onPress={() => setEditing(true)}
              className="h-10 w-10 items-center justify-center rounded-full bg-white/15"
            >
              <Ionicons name="create-outline" size={18} color="#fff" />
            </Pressable>
          ) : (
            <View className="w-10" />
          )}
        </View>

        <View className="mt-4 items-center">
          <Text
            className="text-4xl font-extrabold text-white"
            style={{ fontVariant: ['tabular-nums'] }}
          >
            {sign}
            {formatMoney(txn.amount, txn.currency)}
          </Text>
          <Text className="mt-1 text-xs text-white/80">
            {formatDate(txn.occurred_at, 'long')}
          </Text>
        </View>
      </View>

      <ScrollView
        contentContainerClassName="px-5 py-5 gap-4 pb-10"
        keyboardShouldPersistTaps="handled"
      >
        {isAutoGenerated ? (
          <Card className="gap-3 border border-brand-200 bg-brand-50 p-4 dark:border-brand-700/40 dark:bg-brand-900/30">
            <View className="flex-row items-start gap-2">
              <Ionicons
                name="information-circle"
                size={20}
                color={colors.brand[500]}
              />
              <Text className="flex-1 text-sm text-ink-700 dark:text-ink-100">
                {t('transactions.autoGeneratedBanner')}
              </Text>
            </View>
            {txn.debt_id ? (
              <Button
                label={t('transactions.openDebt')}
                onPress={() =>
                  router.push({ pathname: '/debt/[id]', params: { id: txn.debt_id! } })
                }
                fullWidth
                leftIcon={<Ionicons name="open-outline" size={18} color="#fff" />}
              />
            ) : null}
          </Card>
        ) : null}

        {!editing ? (
          <>
            {contact ? (
              <Card className="flex-row items-center gap-3 p-4">
                <Avatar name={contact.full_name} size={40} />
                <View className="flex-1">
                  <Text className="text-[11px] font-semibold uppercase tracking-widest text-ink-500 dark:text-ink-300">
                    {t('contacts.fullName')}
                  </Text>
                  <Text className="mt-0.5 text-base text-ink-900 dark:text-ink-50">
                    {contact.full_name}
                  </Text>
                </View>
              </Card>
            ) : null}

            {txn.description ? (
              <Card className="p-4">
                <Text className="text-[11px] font-semibold uppercase tracking-widest text-ink-500 dark:text-ink-300">
                  {t('quickAdd.description')}
                </Text>
                <Text className="mt-2 text-base text-ink-700 dark:text-ink-200">
                  {txn.description}
                </Text>
              </Card>
            ) : null}

            {!isAutoGenerated ? (
              <Button
                label={t('transactions.delete')}
                variant="danger"
                onPress={onDelete}
                loading={deleteTxn.isPending}
                fullWidth
                leftIcon={<Ionicons name="trash-outline" size={18} color="#fff" />}
              />
            ) : null}
          </>
        ) : (
          <Card className="gap-4 p-4">
            <Input
              label={t('quickAdd.amount')}
              value={amount}
              onChangeText={setAmount}
              keyboardType="decimal-pad"
              hint={txn.currency}
            />
            <Input
              label={t('quickAdd.description')}
              value={description}
              onChangeText={setDescription}
              multiline
              numberOfLines={3}
            />
            <Button
              label={t('common.save')}
              onPress={onSave}
              loading={saving}
              fullWidth
              size="lg"
            />
          </Card>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}
